# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Развертывание веб-приложения ASP.NET Core в Azure Web App - ValeriyGourovResume

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: ValeriyGourovResume
  AZURE_WEBAPP_PACKAGE_PATH: ${{env.DOTNET_ROOT}}/myapp
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AzureAppService_PublishProfile_eae5998034e344898a1aa008c6868181 }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  #PROJECT_PATH: BlazorApp6

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test app
      run: dotnet test --no-build

    - name: Publish app for deploy
      run: dotnet publish -c ${{ env.CONFIGURATION }} --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
